config/routes.rb
# config/routes.rb

Rails.application.routes.draw do
  ActiveSupport::Deprecation.silence do
    get 'ui(/:action)', controller: 'ui'
  end

  root to: 'pages#front'

  get 'home',   to: 'categories#index'
  get 'videos', to: 'categories#index'

  resources :videos, only: [:show] do
    collection do
      get 'search'
      get 'advanced_search', to: 'videos#advanced_search', as: :advanced_search
    end
    resources :reviews, only: [:create]
  end

  namespace :admin do
    resources :videos, only: [:new, :create]
  end

  resources :categories, only: [:index, :show]

  get 'register',        to: 'users#new'
  get 'register/:token', to: 'users#new_with_invitation_token', as: 'register_with_token'
  resources :users, only: [:create, :show]

  get    'sign_in',  to: 'sessions#new'
  post   'sign_in',  to: 'sessions#create'
  delete 'sign_out', to: 'sessions#destroy'

  get  'my_queue',     to: 'queue_items#index'
  post 'update_queue', to: 'queue_items#update_queue'

  resources :queue_items, only: [:create, :destroy]

  get 'people', to: 'relationships#index'
  resources :relationships, only: [:create, :destroy]

  get 'forgot_password', to: 'forgot_passwords#new'
  resources :forgot_passwords, only: [:create]
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'

  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'pages#expired_token'

  resources :invitations, only: [:new, :create]

  mount StripeEvent::Engine, at: '/stripe_events'
end

app/controllers/forgot_passwords_controller.rb
# app/controllers/forgot_passwords_controller.rb

class ForgotPasswordsController < ApplicationController
  def create
    user = User.find_by email: params[:email]
    if user
      ApplicationMailer.send_forgot_password(user).deliver
      redirect_to forgot_password_confirmation_path
    else
      flash[:error] = params[:email].blank? ? 'Email cannot be blank.' : 'There is no user with that email in the system.'
      redirect_to forgot_password_path
    end
  end

  def confirm
  end
end

app/views/forgot_passwords/confirm.html.haml
/ app/views/forgot_passwords/confirm.html.haml

%section.confirm_password_reset.container
  .row
    .col-sm-10.col-sm-offset-1
      %p We have sent an email with instructions to reset your password.

app/views/forgot_passwords/new.html.haml
%section.forgot_password.container
  .row
    .col-sm-10.col-bg-offset-1
      = form_tag forgot_passwords_path, class: 'sign_in' do
        %header
          %h1 Forgot Password?
          %p We will send you an email with a link that you can use to reset your password.
        .form-group
          = label_tag :email, 'Email Address'
          = text_field_tag :email
        .form-group.action
          %input(type="submit" value="Send Email" class="btn btn-default")