config/routes.rb
# config/routes.rb

Rails.application.routes.draw do
  ActiveSupport::Deprecation.silence do
    get 'ui(/:action)', controller: 'ui'
  end

  root to: 'pages#front'

  get 'home',   to: 'categories#index'
  get 'videos', to: 'categories#index'

  resources :videos, only: [:show] do
    collection do
      get 'search'
      get 'advanced_search', to: 'videos#advanced_search', as: :advanced_search
    end
    resources :reviews, only: [:create]
  end

  namespace :admin do
    resources :videos, only: [:new, :create]
  end

  resources :categories, only: [:index, :show]

  get 'register',        to: 'users#new'
  get 'register/:token', to: 'users#new_with_invitation_token', as: 'register_with_token'
  resources :users, only: [:create, :show]

  get    'sign_in',  to: 'sessions#new'
  post   'sign_in',  to: 'sessions#create'
  delete 'sign_out', to: 'sessions#destroy'

  get  'my_queue',     to: 'queue_items#index'
  post 'update_queue', to: 'queue_items#update_queue'

  resources :queue_items, only: [:create, :destroy]

  get 'people', to: 'relationships#index'
  resources :relationships, only: [:create, :destroy]

  get 'forgot_password', to: 'forgot_passwords#new'
  resources :forgot_passwords, only: [:create]
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'

  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'pages#expired_token'

  resources :invitations, only: [:new, :create]

  mount StripeEvent::Engine, at: '/stripe_events'
end

app/models/user.rb
# app/models/user.rb

class User < ApplicationRecord
  include Tokenable

  has_secure_password validations: false

  has_many :reviews,     -> { order 'created_at DESC' }
  has_many :queue_items, -> { order :position }
  has_many :following_relationships, class_name: 'Relationship', foreign_key: :follower_id
  has_many :leading_relationships,   class_name: 'Relationship', foreign_key: :leader_id

  validates_presence_of   :email, :password, :full_name
  validates_uniqueness_of :email

  def normalize_queue_item_positions
    queue_items.each_with_index do |queue_item, index|
      queue_item.update position: index + 1
    end
  end

  def queued_video? video
    queue_items.map(&:video).include? video
  end

  def follows? another_user
    following_relationships.map(&:leader).include? another_user
  end

  def can_follow? another_user
    !(follows?(another_user) || self == another_user)
  end

  def follow another_user
    following_relationships.create(leader: another_user) if can_follow? another_user
  end
end

app/controllers/users_controller.rb
# app/controllers/users_controller.rb

class UsersController < ApplicationController
  before_action :require_user, only: [:show]

  def new
    redirect_to home_path if signed_in?
    @user = User.new
  end

  def create
    # params.permit!
    @user = User.new user_params
    result = UserSignup.new(@user).sign_up(params[:stripeToken], params[:invitation_token])
    if result.successful?
      flash[:success]   = 'Thank you for registering with MyFlix.'
      session[:user_id] = @user.id
      redirect_to videos_path
    else
      flash[:error] = result.error_message
      render :new
    end
  end

  def show
    @user = User.find params[:id]
  end

  def new_with_invitation_token
    invitation = Invitation.find_by(token: params[:token])
    if invitation
      @invitation_token = invitation.token
      @user             = User.new email: invitation.recipient_email
      render :new
    else
      redirect_to expired_token_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :full_name)
  end
end

app/views/users/___form_backup.html.haml
/ app/views/users/___form_backup.html.haml

      = custom_form_for @user, class: 'form-horizontal' do |f|
        %header
          %h1 Register
        %fieldset
          .form-group
            = f.label :email, 'Email Address', class: 'control-label col-sm-2'
            .col-sm-6
              = f.email_field :email, class: 'form-control'
          .form-group
            = f.label :password, 'Password', class: 'control-label col-sm-2'
            .col-sm-6
              = f.password_field :password, class: 'form-control'
          .form-group
            = f.label :full_name, 'Full Name', class: 'control-label col-sm-2'
            .col-sm-6
              = f.text_field :full_name, class: 'form-control'
          %fieldset.actions.control-group.col-sm-offset-2
            .controls
              = f.submit 'Sign Up', class: 'btn btn-default'

app/views/users/new.html.haml
/ app/views/users/new.html.haml

<script src="https://js.stripe.com/v2/"></script>
<script src="https://checkout.stripe.com/checkout.js"></script>
<script>
Stripe.setPublishableKey("#{ENV['stripe_publishable_key']}")
</script>

= javascript_include_tag 'payment'

%section.register.container
  .row
    .col-sm-10.col-sm-offset-1
      = bootstrap_form_for @user, html: { class: 'form-horizontal', id: 'payment-form' } do |f|
        %header
          %h1 Register
        %fieldset
          = f.email_field :email, label: 'Email Address'
          = f.password_field :password
          = f.text_field :full_name, label: 'Full Name'
          = hidden_field_tag :invitation_token, @invitation_token
        %fieldset.credit_card
          %span.payment-errors
          .form-group
            %label.control-label.col-sm-2(for='credit-card-number') Credit Card Number
            .col-sm-6
              %input.form-control#credit-card-number(type="text" data-stripe='number')
          .form-group
            %label.control-label.col-sm-2(for='security-code') Security Code
            .col-sm-6
              %input.form-control#security-code(type="text" data-stripe='cvc')
          .form-group
            %label.control-label.col-sm-2 Expiration
            .col-sm-3
              = select_month(Date.today, {add_month_numbers: true},  class: 'form-control', data: { stripe: 'exp-month' })
            .col-sm-2
              = select_year(Date.today.year, {start_year: Date.today.year, end_year: Date.today.year + 4}, class: 'form-control', data: { stripe: 'exp-year' })
        %fieldset.actions.control-group.col-sm-offset-2
          .controls
            %input(type="submit" value="Sign Up" class="btn btn-default")

app/views/users/show.html.haml
/ app/views/users/show.html.haml

%section.user.container
  .row
    .col-sm-10.col-sm-offset-1
      %article
        %header
          %img(src="http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest('#{@user.email.downcase}'.downcase)}?s=40")
          %h2 #{@user.full_name}'s video collections (#{@user.queue_items.count})
          = link_to 'Follow', relationships_path(leader_id: @user.id), method: 'post', class: 'btn btn-default' if current_user.can_follow?(@user)
        %table.table
          %thead
            %tr
              %th(width="30%") Video Title
              %th(width="15%") Genre
          %tbody
            - @user.queue_items.each do |queue_item|
              %tr
                %td
                  = link_to queue_item.video.title,   queue_item.video
                %td
                = link_to queue_item.category_name, queue_item.category

%section.user_reviews.container
  .row
    .col-sm-10.col-sm-offset-1
      %header
        %h3 #{@user.full_name}'s Reviews (#{@user.reviews.count})
      %ul
        - @user.reviews.each do |review|
          %article.review
            %li.row
              .col-sm-2
                %p= link_to review.video.title, review.video
                %col Rating: #{review.rating} / 5
              .col-sm-8
                %p= review.content