config/routes.rb
# config/routes.rb

Rails.application.routes.draw do
  ActiveSupport::Deprecation.silence do
    get 'ui(/:action)', controller: 'ui'
  end

  root to: 'pages#front'

  get 'home',   to: 'categories#index'
  get 'videos', to: 'categories#index'

  resources :videos, only: [:show] do
    collection do
      get 'search'
      get 'advanced_search', to: 'videos#advanced_search', as: :advanced_search
    end
    resources :reviews, only: [:create]
  end

  namespace :admin do
    resources :videos, only: [:new, :create]
  end

  resources :categories, only: [:index, :show]

  get 'register',        to: 'users#new'
  get 'register/:token', to: 'users#new_with_invitation_token', as: 'register_with_token'
  resources :users, only: [:create, :show]

  get    'sign_in',  to: 'sessions#new'
  post   'sign_in',  to: 'sessions#create'
  delete 'sign_out', to: 'sessions#destroy'

  get  'my_queue',     to: 'queue_items#index'
  post 'update_queue', to: 'queue_items#update_queue'

  resources :queue_items, only: [:create, :destroy]

  get 'people', to: 'relationships#index'
  resources :relationships, only: [:create, :destroy]

  get 'forgot_password', to: 'forgot_passwords#new'
  resources :forgot_passwords, only: [:create]
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'

  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'pages#expired_token'

  resources :invitations, only: [:new, :create]

  mount StripeEvent::Engine, at: '/stripe_events'
end

app/models/video.rb
# app/models/video.rb

class Video < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  index_name ['myflix', Rails.env].join '_'

  belongs_to :category, optional: true
  has_many   :reviews, -> { order 'created_at DESC' }
  # has_many   :queue_items

  validates_presence_of :title, :description

  mount_uploader :large_cover, LargeCoverUploader
  mount_uploader :small_cover, SmallCoverUploader

  def self.search_by_title title
    return [] if title.blank?
    where('title ~* ?', title).order 'created_at DESC'
  end

  def self.search(query, options = {})
    search_definition = {
      query: {
        bool: {
          must: {
            multi_match: {
              query:    query,
              fields:   ['title^100', 'description^50'],
              operator: 'and'
            }
          }
        }
      }
    }

    if query.present? && options[:reviews].present?
      search_definition[:query][:bool][:must][:multi_match][:fields] << 'reviews.body'
    end

    if options[:rating_from].present? || options[:rating_to].present?
      search_definition[:query][:bool][:filter] = {
        range: {
          average_rating: {
            gte: (options[:rating_from] if options[:rating_from].present?),
            lte: (options[:rating_to]   if options[:rating_to].present?)
          }
        }
      }
    end

    __elasticsearch__.search search_definition
  end

  def rating
    reviews.count > 0 ? average_rating : nil
  end

  def average_rating
    reviews.average(:rating).to_f.round(1) if reviews.any?
  end

  def as_indexed_json(options = {})
    as_json(
      methods: [:average_rating],
      only:    [:title, :description],
      include: {
        reviews: { only: [:body] }
      }
    )
  end
end

app/controllers/admin/videos_controller.rb
# app/controllers/admin/videos_controller.rb

class Admin::VideosController < ApplicationController
  before_action :require_user
  before_action :require_admin

  def new
    @video = Video.new
  end

  def create
    @video = Video.create params.require(:video).permit!
    if @video.save
      flash[:success] = "You have successfully added the video '#{@video.title}'"
      redirect_to new_admin_video_path
    else
      flash[:error] = 'You cannot add this video. Please check the errors.'
      render :new
    end
  end

  private

  def require_admin
    if !current_user.admin?
      flash[:error] = 'You are not authorized to do that.'
      redirect_to home_path
    end
  end
end

app/controllers/videos_controller.rb
# app/controllers/videos_controller.rb

class VideosController < ApplicationController
  before_action :require_user

  def show
    @video = VideoDecorator.decorate(Video.find params[:id])
  end

  def search
    @videos = Video.search_by_title params[:search_term]
  end

  def advanced_search
    options = {
      reviews:     params[:reviews],
      rating_from: params[:rating_from],
      rating_to:   params[:rating_to]
    }

    @videos = if params[:query]
      Video.search(params[:query], options).records.to_a
    else
      []
    end
  end
end

app/views/videos/_video.html.haml
/ app/views/videos/_video.html.haml

.video.col-sm-2
  = link_to video_path(video) do
    %img(src="#{video.small_cover_url}")

app/views/videos/advanced_search.html.haml
/ app/views/videos/advanced_search.html.haml

%section.advanced_search.container
  = form_tag advanced_search_videos_path, class: 'form-horizontal', method: :get do
    %header
      %h1 Advanced Search
    .form-group
      .col-sm-6
        = search_field_tag :query, params[:query], placeholder: 'Search videos by title, description', class: 'form-control'
    .form-group
      .col-sm-6
        .checkbox
          %label
            = check_box_tag :reviews, 'y', params[:reviews] == 'y'
            Include Reviews
    .form-group
      .row.average_rating_label Average Rating
      = label_tag :rating_from, 'From:', class: 'col-sm-1 control-label'
      .col-sm-2
        = select_tag :rating_from, options_for_select((10..50).map { |n| n / 10.0 }, params[:rating_from]), prompt: '-', class: 'form-control'
      = label_tag :rating_to, 'To:', class: 'col-sm-1 control-label'
      .col-sm-2
        = select_tag :rating_to, options_for_select((10..50).map { |n| n / 10.0 }, params[:rating_to]), prompt: '-', class: 'form-control'
    .form-group
      .col-sm-6
        = button_tag(type: "submit", class: "btn btn-primary") do
          %span.glyphicon.glyphicon-search
          Search
  %hr
  - if params[:query].present?
    %h2.results_count Results: #{@videos.count} videos found
    - @videos.each do |video|
      %article.video.row
        .video_data
          %figure.col-sm-2
            %img(src="#{video.small_cover_url}" alt="#{video.title}")
          .video_body.col-sm-10
            %header
              %h3= video.title
            %p.video_description= video.description

app/views/videos/search.html.haml
/ app/views/videos/search.html.haml

%article.video_category
  .videos.row
    = render partial: 'video', collection: @videos

app/views/videos/show.html.haml
/ app/views/videos/show.html.haml

%article.video
  .container
    .row
      .video_large_cover.col-sm-7.col-sm-offset-1
        %img(src="#{@video.large_cover_url}")
      .video_info.col-sm-3
        %header
          %h3= @video.title
          %span Rating:
          = @video.rating
        %p= @video.description
        .actions
          %a.btn.btn-primary(href="#{@video.video_url}") Watch Now
          - unless current_user.queued_video? @video
            = link_to '+ My Queue', queue_items_path(video_id: @video.id), method: :post, class: 'btn btn-default' %section.reviews.container
  .row
    .col-sm-10.col-sm-offset-1
      = bootstrap_form_with model: [@video, Review.new] do |f|
        %fieldset
          .form-group
            .row
              .col-sm-3
                = f.select :rating, [5, 4, 3, 2, 1].map { |n| pluralize n, 'Star' }, { label: 'Rate this video' }, { class: 'selectpicker' }
          .form-group
            .row
              .col-sm-8
                = f.text_area :body, label: 'Write Review', rows: 6, class: 'span6'
        %fieldset.form-group.actions.clearfix
          = f.submit 'Submit', class: 'btn'
          = link_to 'Cancel', ''
      %header
        %h3 User Reviews (#{@video.reviews.count})
      %ul
        - @video.reviews.each do |review|
          %article.review
            %li.row
              .col-sm-2
                %span Rating: #{review.rating} / 5
                %p by #{link_to review.user.full_name, review.user}
              .col-sm-8
                %p= review.body