config/routes.rb
# config/routes.rb

Rails.application.routes.draw do
  ActiveSupport::Deprecation.silence do
    get 'ui(/:action)', controller: 'ui'
  end

  root to: 'pages#front'

  get 'home',   to: 'categories#index'
  get 'videos', to: 'categories#index'

  resources :videos, only: [:show] do
    collection do
      get 'search'
      get 'advanced_search', to: 'videos#advanced_search', as: :advanced_search
    end
    resources :reviews, only: [:create]
  end

  namespace :admin do
    resources :videos, only: [:new, :create]
  end

  resources :categories, only: [:index, :show]

  get 'register',        to: 'users#new'
  get 'register/:token', to: 'users#new_with_invitation_token', as: 'register_with_token'
  resources :users, only: [:create, :show]

  get    'sign_in',  to: 'sessions#new'
  post   'sign_in',  to: 'sessions#create'
  delete 'sign_out', to: 'sessions#destroy'

  get  'my_queue',     to: 'queue_items#index'
  post 'update_queue', to: 'queue_items#update_queue'

  resources :queue_items, only: [:create, :destroy]

  get 'people', to: 'relationships#index'
  resources :relationships, only: [:create, :destroy]

  get 'forgot_password', to: 'forgot_passwords#new'
  resources :forgot_passwords, only: [:create]
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'

  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'pages#expired_token'

  resources :invitations, only: [:new, :create]

  mount StripeEvent::Engine, at: '/stripe_events'
end

app/views/shared/_header.html.haml
/ app/views/shared/_header.html.haml

%section#top-header.row
  %h1.col-md-2
    = link_to 'MyFLiX', root_path
  - if signed_in?
    %ul.col-md-3.clearfix
      %li= link_to 'Videos',          videos_path
      %li= link_to 'My Queue',        my_queue_path
      %li= link_to 'People',          people_path
      %li= link_to 'Advanced Search', advanced_search_videos_path
    = form_tag search_videos_path, method: :get, class: 'col-md-5 navbar-form' do
      = text_field_tag :search_term, nil, placeholder: 'Search for videos here', class: 'form-control'
      = button_tag 'Search', class: 'btn btn-default'
    #user_links.pull-right.col-md-2
      %ul
        %li.dropdown
          %a(href="#" id="dlabel" role="button" data-toggle="dropdown" class="dropdown-toggle" data-target="#")
            Welcome, #{current_user.full_name}
            %b.caret
            %ul.dropdown-menu(role="menu" aria-labelledby="dlabel")
              %li
              - if signed_in?
                = link_to 'Invite a friend', new_invitation_path
                = link_to 'Account', current_user
                %br
                %a(href="#") Plan and Billing
                %br
                = link_to 'Sign Out', sign_out_path, method: 'delete'

app/views/shared/_messages.html.haml
/ app/views/shared/_messages.html.haml

- flash.each do |name, msg|
  %div(class="alert alert-#{name}")
    %a.close(data-dismiss='alert') &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)